### ISSUE TITLE
Internal server error when custom value exists in search relusts

### ISSUE THREAD

**Issue by Dice801** [clear-code/redmine_full_text_search#48]
```
Completed 500 Internal Server Error in 716ms (ActiveRecord: 674.1ms)

ActionView::Template::Error (uninitialized constant Customvalue):
    45:     <h3><%= l(:label_result_plural) %> (<%= @search_result.count %>)</h3>
    46:     <dl id="search-results">
    47:       <% @search_result.each do |e| %>
    48:         <dt class="<%= e.event_type %> icon icon-<%= e.event_type %>">
    49:           <%= content_tag('span', e.project, :class => 'project') unless @project == e.project %>
    50:           <%= link_to(e.event_title_digest, e.event_url, :data => { :rank => e.rank }) %>
    51:         </dt>
  plugins/full_text_search/app/models/full_text_search/searcher_record.rb:220:in `original_record'
  plugins/full_text_search/app/models/full_text_search/searcher_record.rb:254:in `_type'
  lib/plugins/acts_as_event/lib/acts_as_event.rb:64:in `event_type'
  plugins/full_text_search/app/views/search/index.html.erb:48:in `block in _plugins_full_text_search_app_views_search_index_html_erb___1145967650517626388_70308553923880'
  plugins/full_text_search/lib/full_text_search/searcher.rb:116:in `block in each'
  plugins/full_text_search/lib/full_text_search/searcher.rb:115:in `each'
  plugins/full_text_search/lib/full_text_search/searcher.rb:115:in `each'
  plugins/full_text_search/app/views/search/index.html.erb:47:in `_plugins_full_text_search_app_views_search_index_html_erb___1145967650517626388_70308553923880'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

https://github.com/clear-code/redmine_full_text_search/commit/ea09acb790f1e00455f474eb56ed9130f46b1686

0.7.1の変更により customvalue を capitilize した時に、恐らく CustomValue であるべきところが
 Customvalue になっている(vが小文字)ために、検索結果にカスタムフィールドの値が含まれた時にエラーになってしまうと思われます。

**Comment by okkez** [comment]
報告ありがとうございます！
修正して v0.7.2 をリリースしました。

**Comment by Dice801** [comment]
修正ありがとうございました！
アップデートして問題なさそうです。
