### ISSUE TITLE
Can't uninstall full_text_search

### ISSUE THREAD

**Issue by ryouma-nagare** [clear-code/redmine_full_text_search#67]
### 環境情報
- OS：CentOS7.6
- Redmine： 4.0.4.stable.18325
- redmine_full_text_search：commit 9f293f160cf37a921168b6e8e959af9f55d65a49
- groonga：9.0.4
- PGroonga：2.2.0
- Ruby：2.5.5-p157 (2019-03-15) [x86_64-linux]
- Rails：5.2.3
- AppServer：unicorn 5.4.1
- PostgreSQL：11.4

```
bundle exec rake redmine:plugins:migrate RAILS_ENV=production VERSION=0 NAME=full_text_search
```

の実行時に以下のエラーが発生します。

```
== 20170630075028 AddIndexToSearcherRecords: reverting ========================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Index name 'index_searcher_records_pgroonga' on table 'searcher_records' does not exist
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration/compatibility.rb:209:in `index_name_for_remove'
/opt/redmine/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration/compatibility.rb:183:in `remove_index'
```

対処としては以下の通り、ダミーのインデックスを付加してアンインストールしました
```
sudo -u postgres -H psql -d db_redmine --command 'CREATE INDEX index_searcher_records_pgroonga on searcher_records(id) '
```

**Comment by kou** [comment]
できるようにしました。

**Comment by ryouma-nagare** [comment]
こちらも無事にアンインストールできるするようになりました。
