### ISSUE TITLE
Failed to synchronize index

### ISSUE THREAD

**Issue by tsuchm** [clear-code/redmine_full_text_search#74]
```
# bundle exec rake full_text_search:synchronize RAILS_ENV=production
┌ FullTextSearch::Target:All [                                                           ] 1/2465(0%)  4m 9s  9.90/s  0s
└── Journal:New [] 0/0(100%)  0s  0.00/s  0s
└── Journal:Orphan [] 0/0(100%)  0s  0.00/s  0s
└── Journal:Outdated [] 0/0(100%)  0s  0.00/s  0s
└── Issue:New [] 0/0(100%)  0s  0.00/s  0s
└── Issue:Orphan [] 0/0(100%)  0s  0.00/s  0s
└── Issue:Outdated [] 0/0(100%)  0s  0.00/s  0s
└── WikiPage:New [] 0/0(100%)  0s  0.00/s  0s
└── WikiPage:Orphan [] 0/0(100%)  0s  0.00/s  0s
└── WikiPage:Outdated [] 0/0(100%)  0s  0.00/s  0s
└── CustomValue:New [] 0/0(100%)  0s  0.00/s  0s
└── CustomValue:Orphan [] 0/0(100%)  0s  0.00/s  0s
└── CustomValue:Outdated [] 0/0(100%)  0s  0.00/s  0s
└── Project:New [] 0/0(100%)  0s  0.00/s  0s
└── Project:Orphan [] 0/0(100%)  0s  0.00/s  0s
└── Project:Outdated [] 0/0(100%)  0s  0.00/s  0s
└── News:New [] 0/0(100%)  0s  0.00/s  0s
└── News:Orphan [] 0/0(100%)  0s  0.00/s  0s
└── News:Outdated [] 0/0(100%)  0s  0.00/s  0s
└── Document:New [] 0/0(100%)  0s  0.00/s  0s
└── Document:Orphan [] 0/0(100%)  0s  0.00/s  0s
└── Document:Outdated [] 0/0(100%)  0s  0.00/s  0s
└── Message:New [] 0/0(100%)  0s  0.00/s  0s
└── Message:Orphan [] 0/0(100%)  0s  0.00/s  0s
└── Message:Outdated [] 0/0(100%)  0s  0.00/s  0s
└── Attachment:New [                                                                       ] 1/2465(0%) 15s 165.96/s  0s
rake aborted!
NoMethodError: undefined method `delete_prefix' for ".pdf":String
/var/lib/redmine-4.0.5/plugins/redmine_full_text_search/lib/full_text_search/mapper.rb:121:in `extract_tag_ids_from_path'
/var/lib/redmine-4.0.5/plugins/redmine_full_text_search/lib/full_text_search/attachment_mapper.rb:80:in `upsert_fts_target'
/var/lib/redmine-4.0.5/plugins/redmine_full_text_search/lib/full_text_search/batch_runner.rb:113:in `block (2 levels) in synchronize_fts_targets_internal'
/var/lib/gems/2.3.0/gems/tty-progressbar-0.16.0/lib/tty/progressbar.rb:213:in `yield'
/var/lib/gems/2.3.0/gems/tty-progressbar-0.16.0/lib/tty/progressbar.rb:213:in `block (2 levels) in iterate'
/var/lib/gems/2.3.0/gems/tty-progressbar-0.16.0/lib/tty/progressbar.rb:211:in `each'
/var/lib/gems/2.3.0/gems/tty-progressbar-0.16.0/lib/tty/progressbar.rb:211:in `each'
/var/lib/gems/2.3.0/gems/tty-progressbar-0.16.0/lib/tty/progressbar.rb:211:in `block in iterate'
/var/lib/gems/2.3.0/gems/tty-progressbar-0.16.0/lib/tty/progressbar.rb:216:in `each'
/var/lib/gems/2.3.0/gems/tty-progressbar-0.16.0/lib/tty/progressbar.rb:216:in `each'
/var/lib/gems/2.3.0/gems/tty-progressbar-0.16.0/lib/tty/progressbar.rb:216:in `iterate'
/var/lib/redmine-4.0.5/plugins/redmine_full_text_search/lib/full_text_search/batch_runner.rb:105:in `block in synchronize_fts_targets_internal'
/var/lib/redmine-4.0.5/plugins/redmine_full_text_search/lib/full_text_search/resolver.rb:43:in `each'
/var/lib/redmine-4.0.5/plugins/redmine_full_text_search/lib/full_text_search/resolver.rb:43:in `each'
/var/lib/redmine-4.0.5/plugins/redmine_full_text_search/lib/full_text_search/batch_runner.rb:100:in `synchronize_fts_targets_internal'
/var/lib/redmine-4.0.5/plugins/redmine_full_text_search/lib/full_text_search/batch_runner.rb:11:in `synchronize'
/var/lib/redmine-4.0.5/plugins/redmine_full_text_search/lib/tasks/full_text_search.rake:51:in `block (3 levels) in <top (required)>'
/var/lib/redmine-4.0.5/plugins/redmine_full_text_search/lib/tasks/full_text_search.rake:41:in `block (2 levels) in <top (required)>'
/var/lib/redmine-4.0.5/plugins/redmine_full_text_search/lib/tasks/full_text_search.rake:50:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => full_text_search:synchronize
(See full trace by running task with --trace)
```

**Comment by kou** [comment]
I've fixed.

BTW, do you use Debian GNU/Linux stretch?
Ruby 2.3 is EOL. I recommend that you use Ruby 2.4 or later.
Debian GNU/Linux buster provides Ruby 2.5.

**Comment by tsuchm** [comment]
Thanks for your advice.  As far as I know, in order to use Ruby 2.4 or later, it is necessary to upgrade from Stretch to Buster.  It is our future task.
